// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_-V1oSVh6jGgV9dapXxyoyUViiN7aFM',
    appId: '1:372498187678:web:aa508d5d1dff046021c28f',
    messagingSenderId: '372498187678',
    projectId: 'appdev-project-f47a2',
    authDomain: 'appdev-project-f47a2.firebaseapp.com',
    storageBucket: 'appdev-project-f47a2.firebasestorage.app',
    measurementId: 'G-0JPBS8BPKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20nfuttvLSnWKRdng8Ym2psOwwDZ_-KA',
    appId: '1:372498187678:android:855430bc6e2beeab21c28f',
    messagingSenderId: '372498187678',
    projectId: 'appdev-project-f47a2',
    storageBucket: 'appdev-project-f47a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kW7dyUdrc8EnVoeBS1WZ50OTlwTXsmw',
    appId: '1:372498187678:ios:533e1d7d342e96b621c28f',
    messagingSenderId: '372498187678',
    projectId: 'appdev-project-f47a2',
    storageBucket: 'appdev-project-f47a2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kW7dyUdrc8EnVoeBS1WZ50OTlwTXsmw',
    appId: '1:372498187678:ios:533e1d7d342e96b621c28f',
    messagingSenderId: '372498187678',
    projectId: 'appdev-project-f47a2',
    storageBucket: 'appdev-project-f47a2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_-V1oSVh6jGgV9dapXxyoyUViiN7aFM',
    appId: '1:372498187678:web:dd0e51744ce9e3e921c28f',
    messagingSenderId: '372498187678',
    projectId: 'appdev-project-f47a2',
    authDomain: 'appdev-project-f47a2.firebaseapp.com',
    storageBucket: 'appdev-project-f47a2.firebasestorage.app',
    measurementId: 'G-LJDCN8DRW5',
  );

}